### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by kaderisoft** [apinprastya/flutter-internationalize#10]
I followed all the instructions but it didn't work. When you call the class appear null 
Example : loc.homeScreen.title  
homeScreen be null

**Comment by apinprastya** [comment]
That means you does not load the text :)

**Comment by kaderisoft** [comment]
Why the text is not loaded.When using the following code, it works 

`final LocaleBase lBase = LocaleBase; lBase.load('locales/EN_US.json').then((v) { //to read on group main and key sample: print(lBase.main.sample); //to read on group main and key save: print(lBase.main.save); });`

But when using the following code does not work

```
localizationsDelegates: [ const LocDelegate(), GlobalMaterialLocalizations.delegate, GlobalWidgetsLocalizations.delegate, ],

//...

Widget build(BuildContext context) { final loc = Localizations.of<LocaleBase>(context, LocaleBase); print(loc.main.save); print(loc.main.cancel); }
```

**Comment by apinprastya** [comment]
You should debug your code, the problem is on your code. Just check if `Future<LocaleBase> load(Locale locale) async ` is called

**Comment by kaderisoft** [comment]
this is the debug log : 
````
Restarted application in 18,507ms.
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building MyApp(dirty):
flutter: The getter 'main' was called on null.
flutter: Receiver: null
flutter: Tried calling: main
flutter:
flutter: The relevant error-causing widget was:
[38;5;248mflutter:   MyApp[39;49m
flutter:
flutter: When the exception was thrown, this was the stack:
[38;5;244mflutter: #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)[39;49m
[38;5;248mflutter: #1      MyApp.build[39;49m
[38;5;244mflutter: #2      StatelessElement.build[39;49m
[38;5;244mflutter: #3      ComponentElement.performRebuild[39;49m
[38;5;244mflutter: #4      Element.rebuild[39;49m
[38;5;244mflutter: #5      ComponentElement._firstBuild[39;49m
[38;5;244mflutter: #6      ComponentElement.mount[39;49m
[38;5;244mflutter: #7      Element.inflateWidget[39;49m
[38;5;244mflutter: #8      Element.updateChild[39;49m
[38;5;244mflutter: #9      RenderObjectToWidgetElement._rebuild[39;49m
[38;5;244mflutter: #10     RenderObjectToWidgetElement.mount[39;49m
[38;5;244mflutter: #11     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>[39;49m
[38;5;244mflutter: #12     BuildOwner.buildScope[39;49m
[38;5;244mflutter: #13     RenderObjectToWidgetAdapter.attachToRenderTree[39;49m
[38;5;244mflutter: #14     WidgetsBinding.attachRootWidget[39;49m
[38;5;244mflutter: #15     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>[39;49m
[38;5;244mflutter: #24     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:384:19)[39;49m
[38;5;244mflutter: #25     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:418:5)[39;49m
[38;5;244mflutter: #26     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:174:12)[39;49m
flutter: (elided 8 frames from package dart:async and package dart:async-patch)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

[38;5;248m════════ Exception caught by widgets library ═══════════════════════════════════[39;49m
[38;5;244mThe following NoSuchMethodError was thrown building MyApp(dirty):[39;49m
The getter 'main' was called on null.
Receiver: null
Tried calling: main

[38;5;244mThe relevant error-causing widget was[39;49m
    [38;5;248mMyApp[39;49m
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)[39;49m
[38;5;248m#1      MyApp.build[39;49m
[38;5;244m#2      StatelessElement.build[39;49m
[38;5;244m#3      ComponentElement.performRebuild[39;49m
[38;5;244m#4      Element.rebuild[39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Reloaded 1 of 495 libraries in 2,653ms.
```
`

**Comment by kaderisoft** [comment]
The problem was solved....
load the language file then use it 👍  good ext. thank you @apinprastya
